## 异常安全

异常是程序在执行期间产生的问题。C++异常是指在程序运行时发生的特殊情况；异常提供了一种转移程序控制权的方式。
> throw
当问题出现时，程序抛出一个异常
> try
try块中的代码标识是被激活的特定异常，他后面通常跟着一个或多个catch块
> catch
在你想要处理问题的地方，通过异常处理程序捕获异常。catch关键字用于捕获异常。

### throw表达式
抛出异常，即检测是够产生异常。
格式：
`throw 表达式`
异常是一个表达式，其值的类型可以是基本类型，也可以是类。

### try-catch块
try-catch的语句块中，catch可以有多个，但至少一个
> try_catch语句执行的过程：
>> 执行try块中的语句，如果执行的过程中没有异常抛出，那么执行完成之后就执行最后一个catch块中的语句，所以catch块中的语句都不会被执行
>> 如果try块执行的过程中抛出异常，立即跳转到第一个“异常类型”和抛出异常类型匹配的catch块中执行（称为捕获），执行完成后再跳转到最后一个catch块后继续执行。
